### ISSUE TITLE
bug: object has no attribute 'sha512'

### ISSUE THREAD

**Issue by icepaule** [cert-ee/cuckoo3#81]
**Describe the bug**
Uploading a file for analysis throws an error on a fresh install

**To Reproduce**
Freshly install cuckoo3 and submit file for analysis.

**Expected behavior**

** My Cuckoo version and operating system are::**
 Cuckoo 3.0.1, Ubuntu 22.04

**The log, error, files etc can be found at:**
2023-12-28 09:38:53 ERROR [cuckoo.processing.worker]: Failure during processing. error=Failed to run plugin SelectFile. 'File' object has no attribute 'sha512' analysis_id=20231228-U586K6
Traceback (most recent call last):
  File "/opt/cuckoo3/processing/cuckoo/processing/worker.py", line 197, in _run_processing_instances
    data = instance.start()
  File "/opt/cuckoo3/processing/cuckoo/processing/identification/selection.py", line 258, in start
    "sha512": target.sha512,
AttributeError: 'File' object has no attribute 'sha512'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cuckoo3/processing/cuckoo/processing/worker.py", line 231, in _handle_processing
    _run_processing_instances(processing_instances, ctx)
  File "/opt/cuckoo3/processing/cuckoo/processing/worker.py", line 205, in _run_processing_instances
    raise PluginError(
  File "/opt/cuckoo3/processing/cuckoo/processing/worker.py", line 197, in _run_processing_instances
    data = instance.start()
  File "/opt/cuckoo3/processing/cuckoo/processing/identification/selection.py", line 258, in start
    "sha512": target.sha512,
cuckoo.processing.errors.PluginError: Failed to run plugin SelectFile. 'File' object has no attribute 'sha512'
2023-12-28 09:38:53 ERROR [cuckoo.control]: Analysis identification stage failed. analysis_id=20231228-U586K6

**Comment by Hamza-Megahed** [comment]
try to comment line 258 in /opt/cuckoo3/processing/cuckoo/processing/identification/selection.py then start cuckoo again

**Comment by Cryss76** [comment]
This issue was introduced in bfdf572 where sflock is implicitly used to get the sha512-hash, which wasn't supported. The referenced pull request fixes this issue.

**Walkaround until pull-request is accepted:**
```bash
pip uninstall sflock
pip install git+https://github.com/Cryss76/sflock.git@add-sha512
```

**After pull-request is accepted:**
```bash
pip install -U git+https://github.com/cert-ee/sflock
```
If you still have problems rerun the install script.

**Comment by Cryss76** [comment]
@icepaule pls close if the problem was solved with the merge

**Comment by icepaule** [comment]
Neither of the ideas worked for me finaly ...
But it fails later in the process now, but still the same error,
I'll open a new issue with some new log infos.
